---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-system
  namespace: glados
  labels:
    app: glados-system
    context: dojo-chaos
    type: main-entity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-system
      context: dojo-chaos
      type: main-entity
  template:
    metadata:
      labels:
        app: glados-system
        context: dojo-chaos
        type: main-entity
    spec:
      containers:
      - name: glados-system
        image: adbo/glados:0.0.2
        ports:
        - containerPort: 5000
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 5000
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          httpGet:
            path: /status
            port: 5000
        env:
        - name: "ANGER_CONNECTOR"
          value: "anger.core"
        - name: "CURIOSITY_CONNECTOR"
          value: "curiosity.core"
        - name: "INTELLIGENCE_CONNECTOR"
          value: "intelligence.core"
        - name: "MORALITY_CONNECTOR"
          value: "morality.core"
        - name: "PORT"
          value: "5000"

...
---

apiVersion: v1
kind: Service
metadata:
  name: glados
  namespace: glados
spec:
  type: NodePort
  selector:
    app: glados-system
    context: dojo-chaos
    type: main-entity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30017

...
